### ISSUE TITLE
郑商所获取合约出错

### ISSUE THREAD

**Issue by nonotde** [shinnytech/tqsdk-python#334]
Traceback (most recent call last):
  File "/Users/mac/Documents/WORK/python/stock/stock.py", line 37, in <module>
    klines = api.get_kline_serial(wname, 4*60*60)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqsdk/api.py", line 451, in get_kline_serial
    raise Exception("代码 %s 不存在, 请检查合约代码是否填写正确" % (s))
Exception: 代码 CZCE.MA2009 不存在, 请检查合约代码是否填写正确

**Comment by shinny-mayanqiong** [comment]
仔细读文档
http://doc.shinnytech.com/tqsdk/master/usage/mddatas.html?highlight=%E9%83%91%E5%95%86%E6%89%80
郑商所代码：CZCE.MA009
