### ISSUE TITLE
最新版本 2.2 在 python3.6 上运行出错

### ISSUE THREAD

**Issue by lucywang000** [shinnytech/tqsdk-python#391]
系统: mac os 10.15 

重现: 
```python
from tqsdk import (TqApi, TqAccount ,TqKq, TqAuth)
api= TqApi(TqKq(), auth=TqAuth("user", "pass"))
```

报错:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/src/tqsdk/api.py", line 269, in __init__
    self._setup_connection()  # 初始化通讯连接
  File "/src/tqsdk/api.py", line 1995, in _setup_connection
    self._auth.login()  # tqwebhelper 有可能会设置 self._auth
  File "/src/tqsdk/auth.py", line 59, in login
    self._logger.debug("login", user_name=self._user_name)
  File "/src/miniconda3/lib/python3.6/logging/__init__.py", line 1628, in debug
    self.log(DEBUG, msg, *args, **kwargs)
  File "/src/miniconda3/lib/python3.6/logging/__init__.py", line 1672, in log
    self.logger._log(level, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'user_name'
```

换成用 python3.8 之后就好了。

**Comment by shinny-xuyida** [comment]
tqsdk 目前只支持 3.6.4及以上版本的 python使用
