### ISSUE TITLE
Exception: 无法创建复盘服务器

### ISSUE THREAD

**Issue by listplot3d** [shinnytech/tqsdk-python#422]
===简单描述===
用文档里的代码示例,做复盘报错:Exception: 无法创建复盘服务器
(信易账户在试用有效期内,执行请求普通的行情数据没有问题) 

===错误日志===
(py37_quant) xiao@xiao-ws:/mnt/Data/Workspace/python/ats/003_tianqin$  cd /mnt/Data/Workspace/python/ats/003_tianqin ; /usr/bin/env /mnt/Data/System/Programs/anaconda3/envs/py37_quant/bin/python /home/xiao/.vscode/extensions/ms-python.python-2021.10.1317843341/pythonFiles/lib/python/debugpy/launcher 40143 -- /mnt/Data/Workspace/python/ats/003_tianqin/01_temp/pureTest.py 
在使用天勤量化之前，默认您已经知晓并同意以下免责条款，如果不同意请立即停止使用：https://www.shinnytech.com/blog/disclaimer/
Traceback (most recent call last):
  File "/mnt/Data/Workspace/python/ats/003_tianqin/01_temp/pureTest.py", line 4, in <module>
    api = TqApi(backtest = TqReplay(date(2019,12,23)), auth=TqAuth("listplot3d", "123456"))
  File "/mnt/Data/System/Programs/anaconda3/envs/py37_quant/lib/python3.7/site-packages/tqsdk/api.py", line 284, in __init__
    self._setup_connection()  # 初始化通讯连接
  File "/mnt/Data/System/Programs/anaconda3/envs/py37_quant/lib/python3.7/site-packages/tqsdk/api.py", line 2986, in _setup_connection
    self._ins_url, self._md_url = self._backtest._create_server(self)
  File "/mnt/Data/System/Programs/anaconda3/envs/py37_quant/lib/python3.7/site-packages/tqsdk/backtest.py", line 795, in _create_server
    raise Exception("无法创建复盘服务器，请检查复盘日期后重试。")
Exception: 无法创建复盘服务器，请检查复盘日期后重试。
Task was destroyed but it is pending!
task: <Task pending coro=<TqApi._notify_watcher() running at /mnt/Data/System/Programs/anaconda3/envs/py37_quant/lib/python3.7/site-packages/tqsdk/api.py:3442> cb=[TqBaseApi._on_task_done()]>
sys:1: RuntimeWarning: coroutine 'TqApi._notify_watcher' was never awaited

===重现步骤===
基于这里的代码:https://doc.shinnytech.com/tqsdk/latest/usage/replay.html?highlight=%E5%A4%8D%E7%9B%98,改成下面的代码,然后运行:

from datetime import date
from tqsdk import TqApi, TqReplay,TqAuth

api = TqApi(backtest = TqReplay(date(2019,12,23)), auth=TqAuth("用户名", "密码"))
print("hello relay")
api.close()

**Comment by shinny-xuyida** [comment]
复盘服务器目前不推荐使用，可以使用回测或模拟检验策略
