### ISSUE TITLE
官方文档的示例就跑不通 Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by ArtificialZeng** [shinnytech/tqsdk-python#442]
在使用天勤量化之前，默认您已经知晓并同意以下免责条款，如果不同意请立即停止使用：https://www.shinnytech.com/blog/disclaimer/
2022-06-18 12:09:01 -     INFO - 通知 : 与 wss://free-api.shinnytech.com/t/nfmd/front/mobile 的网络连接已建立
204100.0 246
Task was destroyed but it is pending!
task: <Task pending coro=<TqBaseApi._windows_patch() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseApi.py:119> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287C644A2E8>()]> cb=[TqBaseApi._on_task_done()]>
Task was destroyed but it is pending!
task: <Task pending coro=<TqApi._notify_watcher() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\api.py:3604> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287CF30A8B8>()]> cb=[TqBaseApi._on_task_done()]>
Exception ignored in: <coroutine object TqApi._notify_watcher at 0x00000287C63D35C8>
Traceback (most recent call last):
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\api.py", line 3604, in _notify_watcher
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\channel.py", line 143, in __anext__
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\queues.py", line 161, in get
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseApi.py", line 50, in _call_soon
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\base_events.py", line 691, in call_soon
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<TqConnect._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\connect.py:176> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287CF30A9D8>()]> cb=[TqBaseApi._on_task_done()]>
Task was destroyed but it is pending!
task: <Task pending coro=<TqReconnect._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\connect.py:261> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287C644A6D8>()]> cb=[TqBaseApi._on_task_done()]>
Exception ignored in: <coroutine object TqConnect._run at 0x00000287C6374C48>
Traceback (most recent call last):
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\connect.py", line 225, in _run
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\tasks.py", line 589, in sleep
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\events.py", line 726, in get_event_loop_policy
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\events.py", line 719, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
sys:1: RuntimeWarning: coroutine 'WebSocketCommonProtocol.write_close_frame' was never awaited
Task was destroyed but it is pending!
task: <Task pending coro=<TqConnect._send_handler() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\connect.py:232> wait_for=<Future cancelled>>
Exception ignored in: <coroutine object TqReconnect._run at 0x00000287E36762C8>
Traceback (most recent call last):
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\connect.py", line 311, in _run
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseApi.py", line 50, in _call_soon
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\base_events.py", line 691, in call_soon
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<TqReconnect._send_handler() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\connect.py:315> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<TqSymbols._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\symbols.py:29> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287C644A9A8>()]> cb=[TqBaseApi._on_task_done()]>
Task was destroyed but it is pending!
task: <Task pending coro=<TqTradingStatus._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\trading_status.py:26> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287C63DCE28>()]> cb=[TqBaseApi._on_task_done()]>
Task was destroyed but it is pending!
task: <Task pending coro=<BaseSim._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\tradeable\sim\basesim.py:78> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287CC01F978>()]> cb=[TqBaseApi._on_task_done()]>
Task was destroyed but it is pending!
task: <Task pending coro=<TqWebHelper._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\tqwebhelper.py:80> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287CF30AA98>()]> cb=[TqBaseApi._on_task_done()]>
Task was destroyed but it is pending!
task: <Task pending coro=<DataExtension._run() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\data_extension.py:82> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000287CF30AD08>()]> cb=[TqBaseApi._on_task_done()]>
Exception ignored in: <coroutine object TqSymbols._run at 0x00000287C63D36C8>
Traceback (most recent call last):
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\symbols.py", line 63, in _run
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseApi.py", line 50, in _call_soon
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\base_events.py", line 691, in call_soon
  File "H:\A_software\Anaconda3\envs\pp212\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<TqSymbols._sim_handler() running at H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\symbols.py:68> wait_for=<Future cancelled>>
Exception ignored in: <coroutine object TqTradingStatus._run at 0x00000287C63D37C8>
Traceback (most recent call last):
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\trading_status.py", line 26, in _run
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseModule.py", line 47, in _run
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseModule.py", line 47, in <listcomp>
  File "H:\A_software\Anaconda3\envs\pp212\lib\site-packages\tqsdk\baseApi.py", line 50, in _call_soon
  File "H:\A_software\Anaconda3\

**Comment by shinny-xuyida** [comment]
结尾加个
api.close()
